apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-cosign
spec:
  name: cosign
  artifactTypes: application/vnd.dev.cosign.artifact.sig.v1+json
  parameters:
    trustPolicies:
    - name: cosignpolicy
      scopes:
      keyless:
        # ctLogVerify:
        # certificateIdentity: 
        certificateIdentityRegExp: "[A-Za-z0-9._-]+@excid.io"
        certificateOIDCIssuer: "https://token.actions.githubusercontent.com" 
        # certificateOIDCIssuerRegExp:
    # rekorURL: https://rekor.sigstore.dev
---
apiVersion: config.ratify.deislabs.io/v1beta1
kind: Store
metadata:
  name: store-oras
spec:
  name: oras
  parameters:
    cacheEnabled: true
    cosignEnabled: true
    ttl: 10