# https://ratify.dev/docs/plugins/verifier/cosign/#configuration
apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-cosign
spec:
  name: cosign
  artifactTypes: application/vnd.dev.cosign.artifact.sig.v1+json
  parameters:
    trustPolicies:
    - name: cosignpolicy
      # tLogVerify: # OPTIONAL: [boolean] enables/disables transparency log verification. default is 'true'
      scopes:
        - "registry.gitlab.com/lefosg"
      keyless:
        # ctLogVerify:  # OPTIONAL: [boolean] enables/disables certificate transparency log verification. default is 'true'
        # certificateIdentity: 
        certificateIdentityRegExp: "[A-Za-z0-9._-]+@exccid.io"
        certificateOIDCIssuer: "https://token.actions.githubusercontent.com" 
        # certificateOIDCIssuerRegExp:
---
apiVersion: config.ratify.deislabs.io/v1beta1
kind: Store
metadata:
  name: store-oras
spec:
  name: oras
  parameters:
    cacheEnabled: true
    cosignEnabled: true
    ttl: 10