--- 
apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  url: https://open-policy-agent.github.io/gatekeeper/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 5m
  releaseName: gatekeeper
  chart:
    spec:
      chart: gatekeeper
      version: 3.10.0
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: gatekeeper-system
  values:
    enableExternalData: true
    controllerManager:
      dnsPolicy: ClusterFirst
    audit:
      dnsPolicy: ClusterFirst
  install:
    createNamespace: true
