apiVersion: apps/v1
kind: Deployment
metadata:
  name: excid-cicd-demo-project
  labels:
    app: excid-cicd-demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excid-cicd-demo-project
  template:
    metadata:
      labels:
        app: excid-cicd-demo-project
    spec:
      containers:
      - name: excid-cicd-demo-project
        image: registry.gitlab.com/lefosg/excid-cicd-demo-project:latest # Specify the tag if needed
        ports:
        - containerPort: 9090 # Change this to the port your application listens on
        # env:
        # - name: HTTP_PORT
        #   value: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: excid-cicd-demo-project
spec:
  type: ClusterIP # Change to LoadBalancer or NodePort if needed
  ports:
  - port: 9090 # The port that the service will expose
    targetPort: 9090 # The port on the container
  selector:
    app: excid-cicd-demo-project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: excid-cicd-demo-project
  namespace: default
  labels:
    app: excid-cicd-demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excid-cicd-demo-project
  template:
    metadata:
      labels:
        app: excid-cicd-demo-project
    spec:
      containers:
      - name: excid-cicd-demo-project
        image: registry.gitlab.com/lefosg/excid-cicd-demo-project:latest # Specify the tag if needed
        ports:
        - containerPort: 9090 # Change this to the port your application listens on
        # env:
        # - name: HTTP_PORT
        #   value: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: excid-cicd-demo-project
  namespace: default
spec:
  type: ClusterIP # Change to LoadBalancer or NodePort if needed
  ports:
  - port: 9090 # The port that the service will expose
    targetPort: 9090 # The port on the container
  selector:
    app: excid-cicd-demo-project
