apiVersion: apps/v1
kind: Deployment
metadata:
  name: valid-deployment
  labels:
    app: valid-deployment
spec:
  replicas: 0 # testing purposes only
  selector:
    matchLabels:
      app: valid-deployment
  template:
    metadata:
      labels:
        app: valid-deployment
    spec:
      containers:
      - name: valid
        image: registry.gitlab.com/excid-demo/excid-cicd-demo-project/apline:signed  
        #kubectl logs cosign-gatekeeper-provider-649d557949-nfsjc -n cosign-gatekeeper-provider
