apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: excid-cicd-demo-project
    path: prod_replicas.yaml