apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: excid-image-repo
  namespace: flux-system
spec:
  image: registry.gitlab.com/lefosg/excid-cicd-demo-project
  interval: 1m0s
  provider: generic
