---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: excid-image-repo-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: excid-image-repo
  policy:
    semver:
      range: 6.0.x
