apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SbomValidation
metadata:
  name: sbom-validation-constraint
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["default"]