apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NotationIssuerValidation
metadata:
  name: localhost-signature-validation
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["*"]
  parameters:
    issuer: "localhost:5000"
