apiVersion: apps/v1
kind: Deployment
metadata:
  name: excid-cicd-demo-project
  namespace: default
  labels:
    app: excid-cicd-demo-project
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: excid-cicd-demo-project
  template:
    metadata:
      labels:
        app: excid-cicd-demo-project
    spec:
      containers:
      - name: excid-cicd-demo-project
        image: registry.gitlab.com/lefosg/excid-cicd-demo-project:1.0.6 # {"$imagepolicy": "flux-system:excid-image-policy"}
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: excid-cicd-demo-project
  namespace: default
spec:
  type: ClusterIP 
  ports:
  - port: 9090
    targetPort: 9090 
  selector:
    app: excid-cicd-demo-project
