apiVersion: apps/v1
kind: Deployment
metadata:
  name: excid-cicd-demo-project-unsigned
  namespace: default
  labels:
    app: excid-cicd-demo-project-unsigned
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: excid-cicd-demo-project-unsigned
  template:
    metadata:
      labels:
        app: excid-cicd-demo-project-unsigned
    spec:
      containers:
      - name: excid-cicd-demo-project-unsigned
        image: registry.gitlab.com/lefosg/excid-cicd-demo-project:unsigned
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: excid-cicd-demo-project-unsigned
  namespace: default
spec:
  type: ClusterIP 
  ports:
  - port: 9090
    targetPort: 9090 
  selector:
    app: excid-cicd-demo-project-unsigned
