apiVersion: v1
kind: Pod
metadata:
  name: excid-cicd-demo-project
  labels:
    app: excid-cicd-demo-project
spec:
  containers:
    - name: excid-cicd-demo-project
      image: registry.gitlab.com/excid-demo/excid-cicd-demo-project:latest
      ports:
        - containerPort: 80
  restartPolicy: Always