name: Build Container Image

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/ci.yaml
      - Dockerfile

jobs:
  scan-build-and-push-image:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'
      - name: NodeJS Scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3.3.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/excid-io/seccon-dev:latest
          context: .
      
      - name: STaaS Sign Container Image
        env:
          COMMENT: gh-actions-sign-image-$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        run: |
          wget https://github.com/excid-io/staas-cli/releases/download/main/staas-cli
          chmod +x ./staas-cli
          ./staas-cli sign-image ghcr.io/excid-io/seccon-dev:latest --token ${{ secrets.STAAS_API_KEY }} --comment $COMMENT

