# Documentation: https://kyverno.io/docs/policy-types/cluster-policy/verify-images/sigstore/#keyless-signing-and-verification
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image-keyless
spec:
  webhookConfiguration:
    timeoutSeconds: 30
  rules:
    - name: check-image-keyless
      match:
        any:
        - resources:
            kinds:
              - Deployment
      verifyImages:
      - imageReferences:
        - "registry.gitlab.com/lefosg/excid-cicd-demo-project:*"
        failureAction: Enforce
        attestations:
        - predicateType: https://cyclonedx.org/schema
          attestors:
          - entries:
            - keyless:
                subject: "https://gitlab.com/lefosg/excid-cicd-demo-project//.gitlab-ci.yml@refs/heads/main"
                issuer: "https://gitlab.com"
                # subjectRegExp: 
                # issuerRegExp: 
                rekor:
                  url: https://rekor.sigstore.dev
          conditions:
          - all:
            - key: "{{ Data.bomFormat }}"
              operator: Equals
              value: CycloneDX
