apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NotationNestedValidation
metadata:
  name: notation-nested-constraint
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["default"]
